/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.medical.screen;

import me.medical.controller.Conexao;
import me.medical.utils.Msg;
import me.medical.utils.Utils;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Adriano Zanette
 */
public class TelaGeralPedidosMedicacao extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaPacientesCadSistema
     */
    public TelaGeralPedidosMedicacao() {
        initComponents();
        listarSolicitacao();
        pintarColumnaTabla();
        setIcon();
        //panel2.setBackground(new Color(0,153,204,200));
        conexao = Conexao.conector();
    }

    void pintarColumnaTabla() {
        ColorearFilasSolicitacao color = new ColorearFilasSolicitacao(5);
        jTableSolicitacao.getColumnModel().getColumn(5).setCellRenderer(color);
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Receita.png")));
    }

    public void listarSolicitacao() {
        Conexao conec = new Conexao();
        DefaultTableModel model = (DefaultTableModel) jTableSolicitacao.getModel();
        model.setNumRows(0);
        String sql = "Select codigo,DataPedido,setorHospitalar,TipoMedicacao,Solicitante,StatusEntrega from tb_Solicitacao order by codigo";
        try {
            pst = Conexao.conector().prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("codigo"),
                    Utils.convertData(rs.getDate("DataPedido")),
                    rs.getString("setorHospitalar"),
                    rs.getString("TipoMedicacao"),
                    rs.getString("Solicitante"),
                    rs.getString("StatusEntrega"),});
            }
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);
        } finally {
            try {
                rs.close();
                pst.close();
                conec.desconectar();
            } catch (Exception ex) {
            }
        }

    }

    public void pesquisarSetor() {
        DefaultTableModel model = (DefaultTableModel) jTableSolicitacao.getModel();
        model.setNumRows(0);
        //conexão com o banco de dados
        Conexao conec = new Conexao();
        String sql = "Select *from tb_Solicitacao where setorHospitalar like ?";
        try {
            pst = Conexao.conector().prepareStatement(sql);
            pst.setString(1, txtPesquisar.getText() + "%");
            rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("codigo"),
                    Utils.convertData(rs.getDate("DataPedido")),
                    rs.getString("setorHospitalar"),
                    rs.getString("TipoMedicacao"),
                    rs.getString("Solicitante"),
                    rs.getString("StatusEntrega"),});
            }
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, error);
        } finally {
            try {
                rs.close();
                pst.close();
                conec.desconectar();
            } catch (Exception ex) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSolicitacao = new javax.swing.JTable();
        btnLegenda = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Solicitação de Medicação");
        setExtendedState(MAXIMIZED_BOTH);

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        jLabel1.setText("Pesquisa por Setor");

        jXTitledPanel1.setTitle("Clique sobre a LINHA desejada para ALTERAÇÃO");
        jXTitledPanel1.setTitleFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jXTitledPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTableSolicitacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data Pedido", "Setor", "Medicação Solicitada", "Solicitante", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSolicitacao.setFocusable(false);
        jTableSolicitacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSolicitacaoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableSolicitacaoMouseReleased(evt);
            }
        });
        jTableSolicitacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableSolicitacaoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSolicitacao);
        if (jTableSolicitacao.getColumnModel().getColumnCount() > 0) {
            jTableSolicitacao.getColumnModel().getColumn(0).setMinWidth(70);
            jTableSolicitacao.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTableSolicitacao.getColumnModel().getColumn(0).setMaxWidth(70);
            jTableSolicitacao.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableSolicitacao.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableSolicitacao.getColumnModel().getColumn(2).setMinWidth(100);
            jTableSolicitacao.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableSolicitacao.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableSolicitacao.getColumnModel().getColumn(4).setMinWidth(150);
            jTableSolicitacao.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableSolicitacao.getColumnModel().getColumn(4).setMaxWidth(150);
            jTableSolicitacao.getColumnModel().getColumn(5).setMinWidth(100);
            jTableSolicitacao.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableSolicitacao.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTitledPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnLegenda.setBackground(new java.awt.Color(51, 153, 255));
        btnLegenda.setForeground(new java.awt.Color(255, 255, 255));
        btnLegenda.setLabel("Atualizar TB");
        btnLegenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLegendaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/Sair.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLegenda, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLegenda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1026, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //chama a tela qque possui os dados e serao setados abaixo
    TelaAlterarPedidoMedicacao tela = new TelaAlterarPedidoMedicacao();

    private void alterar() {
        //chama a tela ja com os dados
        //tela = new TelaInternacao(this);
        // chama a tela ja com os dados
        int index = jTableSolicitacao.getSelectedRow();
        TableModel model = jTableSolicitacao.getModel();
        String Codigo = model.getValueAt(index, 0).toString();
        String DataPedido = model.getValueAt(index, 1).toString();
        String Setor = model.getValueAt(index, 2).toString();
        String TipoMedicacao = model.getValueAt(index, 3).toString();
        String Solicitante = model.getValueAt(index, 4).toString();
        String StatusEntrega = model.getValueAt(index, 5).toString();
        tela.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        tela.txtCodigo.setText(Codigo);
        tela.txtDataPedido.setText(DataPedido);
        tela.JcSetorPedido.setText(Setor);
        tela.JcPedidoMedicacao.setText(TipoMedicacao);
        tela.txtSolicitante.setText(Solicitante);
        tela.JcStatus.setSelectedItem(StatusEntrega);

        //tela.txtDataEntrega.getEditor().setText(DataEntrega);
        tela.setVisible(true);
        tela.btnSalvar.setEnabled(true);
        tela.pack();
    }

    private void excluir(int id) {
        Conexao conec = new Conexao();
        String sql = "DELETE FROM `consultorio`.`tb_solicitacao` WHERE  `codigo`=" + id + ";";

        try {
            pst = Conexao.conector().prepareStatement(sql);
            pst.executeUpdate();
            rs.close();
            pst.close();
            conec.desconectar();
            listarSolicitacao();
            Msg.informacao(this, "Excluido com Sucesso!");
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, error);
        }
    }


    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        pesquisarSetor();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void jTableSolicitacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSolicitacaoMouseClicked
        if (evt.getClickCount() == 1) {
            // chama a tela ja com os dados
            alterar();
            
            
            
        }
    }//GEN-LAST:event_jTableSolicitacaoMouseClicked

    private void jTableSolicitacaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSolicitacaoMouseReleased

    }//GEN-LAST:event_jTableSolicitacaoMouseReleased

    private void jTableSolicitacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableSolicitacaoKeyReleased

    }//GEN-LAST:event_jTableSolicitacaoKeyReleased

    private void btnLegendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLegendaActionPerformed
        listarSolicitacao();
    }//GEN-LAST:event_btnLegendaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int i = jTableSolicitacao.getSelectedRow();
        if (i < 0) {
            Msg.alerta(this, "Selecione um Registro!");
            jTableSolicitacao.setEnabled(true);
            return;
        } else {
            if (Msg.confirmar(this, "Deseja Realmente Excluir Este Registro?")) {
                excluir(Integer.parseInt(jTableSolicitacao.getValueAt(i, 0).toString()));
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGeralPedidosMedicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGeralPedidosMedicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGeralPedidosMedicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGeralPedidosMedicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGeralPedidosMedicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private java.awt.Button btnLegenda;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSolicitacao;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables


  

}
