/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.medical.screen;

//import DAO.ESPECIALIDADES_DAO;
//import DAO.PACIENTE_DAO;
import me.medical.dao.ESPECIALIDADES_DAO;
import me.medical.dao.SERVICOS_DAO;
//import MODEL.PACIENTE_MODEL;
import me.medical.model.ESPECIALIDADES_MODEL;
import me.medical.model.SERVICOS_MODEL;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.TimerTask;
import java.util.Timer;
import javax.swing.table.DefaultTableModel;
import me.medical.utils.ColorearFilasEspecialidades;

/**
 *
 * @author Adriano Zanette
 */
public class TelaExibirServicos extends javax.swing.JFrame {
   int segundos = 0;
 
    int ID = 0;
    List<ESPECIALIDADES_MODEL> LISTA_COMPLETA = new ArrayList<>();
    List<SERVICOS_MODEL> LISTA_COMPLETAS = new ArrayList<>();
    public Connection CONEXAO = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaExibirServicos
     */
    public TelaExibirServicos() {
        initComponents();
        pintarColumnaTablaServicos();
        pintarColumnaTabla();
        setIcon();
        PREENCHER_TABELA_ESPECIALIDADES();
        PREENCHER_TABELA_SERVICOS();

        //FECHA DEL SISTEMA
        Date Hora = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Data.setText(formato.format(Hora));

        //HORA DEL SISTEMA
//        Timer tempo = new Timer(100, new TelaExibirServicos.horas());
//        tempo.start();
        Horario();
    }

    private void pintarColumnaTablaServicos() {
        me.medical.screen.ColorearFilasServicos color = new me.medical.screen.ColorearFilasServicos(2);
        TabelaServicos.getColumnModel().getColumn(2).setCellRenderer(color);
    }
    
    private void pintarColumnaTabla() {
        me.medical.screen.ColorearFilasServicos color = new me.medical.screen.ColorearFilasServicos(4);
        TabelaEspecialidades.getColumnModel().getColumn(4).setCellRenderer(color);
    }
    

    class horas implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Date Hora = new Date();
            String AmPm = "HH:mm:ss";
            SimpleDateFormat format = new SimpleDateFormat(AmPm);
            Calendar hoje = Calendar.getInstance();
            hora1.setText(String.format(format.format(Hora), hoje));
        }
    }

    // MUDAR ICONE TELA
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Receita.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Data = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaEspecialidades = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaServicos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        hora1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Exibição de Serviços");
        setExtendedState(6);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ATENDIMENTOS DISPONÍVEIS NA DATA DE HOJE");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/logoHospital.jpg"))); // NOI18N

        Data.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Data.setForeground(new java.awt.Color(255, 0, 0));
        Data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Data))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Data)
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TabelaEspecialidades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaEspecialidades.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TabelaEspecialidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sigla", "Nome do Médico", "Especialidades Médicas", "Turno de Trabalho", "Status de Atendimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaEspecialidades.setRowHeight(25);
        jScrollPane3.setViewportView(TabelaEspecialidades);
        if (TabelaEspecialidades.getColumnModel().getColumnCount() > 0) {
            TabelaEspecialidades.getColumnModel().getColumn(0).setMinWidth(50);
            TabelaEspecialidades.getColumnModel().getColumn(0).setPreferredWidth(50);
            TabelaEspecialidades.getColumnModel().getColumn(0).setMaxWidth(50);
            TabelaEspecialidades.getColumnModel().getColumn(1).setPreferredWidth(200);
            TabelaEspecialidades.getColumnModel().getColumn(2).setPreferredWidth(140);
            TabelaEspecialidades.getColumnModel().getColumn(3).setMinWidth(0);
            TabelaEspecialidades.getColumnModel().getColumn(3).setPreferredWidth(0);
            TabelaEspecialidades.getColumnModel().getColumn(3).setMaxWidth(0);
            TabelaEspecialidades.getColumnModel().getColumn(4).setPreferredWidth(145);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TabelaServicos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo de Servico", "Turno do Serviço", "Status do Serviço"
            }
        ));
        TabelaServicos.setRowHeight(25);
        jScrollPane2.setViewportView(TabelaServicos);
        if (TabelaServicos.getColumnModel().getColumnCount() > 0) {
            TabelaServicos.getColumnModel().getColumn(0).setPreferredWidth(100);
            TabelaServicos.getColumnModel().getColumn(1).setPreferredWidth(40);
            TabelaServicos.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hora1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hora1.setForeground(new java.awt.Color(255, 0, 0));
        hora1.setText("jLabel5");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ATENDIMENTO - 24 HORAS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hora1)
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hora1)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExibirServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExibirServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExibirServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExibirServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExibirServicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Data;
    private javax.swing.JTable TabelaEspecialidades;
    private javax.swing.JTable TabelaServicos;
    private javax.swing.JLabel hora1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

     public void Horario() {
        segundos = 0;
        Timer timer = null;
        final SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        if (timer == null) {
            timer = new Timer();
            TimerTask tarefa = new TimerTask() {
                @Override
                public void run() {
                    try {
                       
                        segundos++;
                        if(segundos>=25){
                            segundos=0;
//                            JOptionPane.showMessageDialog(null, "Deve atualizar");
                            System.err.println("Relogio: "+format.format(new Date().getTime()));
                           
                           ATUALIZA_DADOS(); 
                        }
//                            hora1.setText("" + hor);
                          hora1.setText(format.format(new Date().getTime()));
                    
                    } catch (Exception e) {
                        System.err.println("Erro ao Processar Hora: " + e);
//                        e.printStackTrace();
                    }
                }
            };
            timer.scheduleAtFixedRate(tarefa, 10, 1000);

        }

    }
    
    

    public void ATUALIZA_DADOS(){
    PREENCHER_TABELA_ESPECIALIDADES();   
    PREENCHER_TABELA_SERVICOS();
    }
    
    
    private void PREENCHER_TABELA_ESPECIALIDADES() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaEspecialidades.getModel();
        modelo.setNumRows(0);
        ESPECIALIDADES_DAO dao = new ESPECIALIDADES_DAO();
        List<ESPECIALIDADES_MODEL> lista_dao = dao.LISTA_COMPLETA();
        LISTA_COMPLETA = lista_dao;

        if (lista_dao.size() > 0) {
            for (ESPECIALIDADES_MODEL especialidades_model : lista_dao) {
                modelo.addRow(new Object[]{
                    especialidades_model.getSigla(),
                    especialidades_model.getNomeMedico(),
                    especialidades_model.getEspecialidades(),
                    especialidades_model.getTurnoEspecialidade(),
                    especialidades_model.getStatusEspecialidade(),});
            }
            pintarColumnaTabla();
            
        }
    }

    private void PREENCHER_TABELA_SERVICOS() {

//        JTableHeader Theader = table.getJTableHeader();
        DefaultTableModel modelo = (DefaultTableModel) TabelaServicos.getModel();
        modelo.setNumRows(0);
        SERVICOS_DAO dao = new SERVICOS_DAO();
        List<SERVICOS_MODEL> lista_dao = dao.LISTA_COMPLETA();
        LISTA_COMPLETAS = lista_dao;

        if (lista_dao.size() > 0) {
            for (SERVICOS_MODEL servicos_model : lista_dao) {
                modelo.addRow(new Object[]{
                    servicos_model.getTipoServico(),
                    servicos_model.getTurnoServico(),
                    servicos_model.getStatusServico(),});

            }
            pintarColumnaTablaServicos();
            
        }
    }
}
