/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.medical.screen;

import me.medical.dao.FUNCOES_DAO;
import me.medical.model.FUNCOES_MODEL;
import me.medical.utils.UpperCaseField;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adriano Zanette
 */
public class TelaCadFuncoes extends javax.swing.JFrame {

    int ID = 0;
    List<FUNCOES_MODEL> LISTA_COMPLETA = new ArrayList<>();
    public Connection CONEXAO = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaCadEspecialidadesMedicas
     */
    public TelaCadFuncoes() {
        initComponents();
        setIcon();
        PREENCHER_TABELA();
        txtNomeServidor.setDocument(new UpperCaseField(100));
        letrasemNegrito();
        txtCodigo.setEnabled(false);
        txtNomeServidor.setEnabled(false);
        TabelaFuncoes.setEnabled(false);
        jcSigla.setEnabled(false);
//        btnPesquisar.setEnabled(false);
        btnDeletar.setEnabled(false);
        btnSalvar.setEnabled(false);
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Receita.png")));
    }

    private void Limpar() {
        txtCodigo.setText("");
        txtNomeServidor.setText("");
    }
    
    
    // metodo para colocar a letra em negrito
    Font fonte = new Font("Arial", Font.BOLD, 12);

    private void letrasemNegrito() {
        txtNomeServidor.setFont(fonte);
        jcSigla.setFont(fonte);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNomeServidor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcSigla = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnovo = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFuncoes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Funções");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro Funções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        jpCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Sigla:");
        jpCadastro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome do Médico:");
        jpCadastro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(255, 255, 204));
        txtCodigo.setToolTipText("Código do tipo do produto");
        txtCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jpCadastro.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 30));

        txtNomeServidor.setBackground(new java.awt.Color(255, 255, 204));
        txtNomeServidor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jpCadastro.add(txtNomeServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 320, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Código :");
        jpCadastro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jcSigla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Dr", "Dra" }));
        jcSigla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpCadastro.add(jcSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 140, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSalvar.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/salvar_1.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/Novo.png"))); // NOI18N
        btnovo.setText("Novo");
        btnovo.setToolTipText("Novo");
        btnovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnovo.setPreferredSize(new java.awt.Dimension(80, 80));
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/LIMPAR.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.setToolTipText("Deletar");
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        TabelaFuncoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Sigla", "Nome Atendente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaFuncoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFuncoesMouseClicked(evt);
            }
        });
        TabelaFuncoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaFuncoesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaFuncoes);
        if (TabelaFuncoes.getColumnModel().getColumnCount() > 0) {
            TabelaFuncoes.getColumnModel().getColumn(0).setMinWidth(0);
            TabelaFuncoes.getColumnModel().getColumn(0).setPreferredWidth(0);
            TabelaFuncoes.getColumnModel().getColumn(0).setMaxWidth(0);
            TabelaFuncoes.getColumnModel().getColumn(1).setPreferredWidth(50);
            TabelaFuncoes.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 590, 380));

        setSize(new java.awt.Dimension(628, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        GRAVACAO();
        jcSigla.setSelectedIndex(0);
        jcSigla.setEnabled(false);
        txtNomeServidor.setEnabled(false);

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        txtNomeServidor.setEnabled(true);
        TabelaFuncoes.setEnabled(true);
        jcSigla.setEnabled(true);
        Limpar();
        btnovo.setEnabled(false);
        btnDeletar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnSalvar.setText("Salvar");
//        btnPesquisar.setEnabled(true);
        txtNomeServidor.requestFocus();

    }//GEN-LAST:event_btnovoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        int pergunta = JOptionPane.showConfirmDialog(null, "Confirma exclusão?");
        if (pergunta == JOptionPane.YES_OPTION) {
            EXCLUIR();
            Limpar();
            jcSigla.setSelectedIndex(0);
            jcSigla.setEnabled(false);
            txtNomeServidor.setEnabled(false);

        }

    }//GEN-LAST:event_btnDeletarActionPerformed

    private void TabelaFuncoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaFuncoesMouseClicked
        int linha = TabelaFuncoes.getSelectedRow();
        if (linha >= 0) {
            ID = Integer.parseInt(TabelaFuncoes.getValueAt(linha, 0).toString());
            //PESQUISA_COD_VISUAL();
            PESQUISA_COD_VISUAL_MEMORIA_FUNCOES(linha);
            btnDeletar.setEnabled(true);
            btnSalvar.setEnabled(true);
            btnSalvar.setText("Alterar");
            btnovo.setEnabled(false);
        }
    }//GEN-LAST:event_TabelaFuncoesMouseClicked

    private void TabelaFuncoesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaFuncoesKeyReleased
        int linha = TabelaFuncoes.getSelectedRow();
        if (linha >= 0) {
            ID = Integer.parseInt(TabelaFuncoes.getValueAt(linha, 0).toString());
            //           PESQUISA_COD_VISUAL();
            PESQUISA_COD_VISUAL_MEMORIA_FUNCOES(linha);
            btnDeletar.setEnabled(true);
        }
    }//GEN-LAST:event_TabelaFuncoesKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadFuncoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadFuncoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadFuncoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadFuncoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadFuncoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaFuncoes;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcSigla;
    private javax.swing.JPanel jpCadastro;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNomeServidor;
    // End of variables declaration//GEN-END:variables

    private void GRAVACAO() {

        if (jcSigla.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecione a sigla", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txtNomeServidor.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O nome do servidor é obrigatório", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtNomeServidor.requestFocus();
            return;
        }

        FUNCOES_MODEL model = new FUNCOES_MODEL();
        model.setSigla(jcSigla.getSelectedItem().toString());
        model.setNomeServidor(txtNomeServidor.getText());
        model.setCodigo(ID);
        FUNCOES_DAO dao = new FUNCOES_DAO();

        if (ID == 0) {
            dao.GRAVAR(model);
            Limpar();
            btnSalvar.setEnabled(false);
            btnDeletar.setEnabled(false);
            btnovo.setEnabled(true);
            txtNomeServidor.setEnabled(false);
            TabelaFuncoes.setEnabled(false);
            jcSigla.setEnabled(false);
            jcSigla.setSelectedIndex(0);
        } else {
            dao.ALTERAR(model);
            Limpar();
            btnSalvar.setEnabled(false);
            btnDeletar.setEnabled(false);
            btnovo.setEnabled(true);
            txtNomeServidor.setEnabled(false);
            TabelaFuncoes.setEnabled(false);
            jcSigla.setEnabled(false);
            jcSigla.setSelectedIndex(0);
        }
        PREENCHER_TABELA();

    }

    private void PREENCHER_TABELA() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaFuncoes.getModel();
        modelo.setNumRows(0);

        FUNCOES_DAO dao = new FUNCOES_DAO();
        List<FUNCOES_MODEL> lista_dao = dao.LISTA_COMPLETA();
        LISTA_COMPLETA = lista_dao;

        if (lista_dao.size() > 0) {
            for (FUNCOES_MODEL funcoes_model : lista_dao) {
                modelo.addRow(new Object[]{
                    funcoes_model.getCodigo(),
                    funcoes_model.getSigla(),
                    funcoes_model.getNomeServidor(),});

            }

        }
    }

    // CLICA NA TABELA E PREENCHE OS CAMPOS
    // seta os dados na tabela
    private void PESQUISA_COD_VISUAL_MEMORIA_FUNCOES(int linha) {
        // PUXA DIRETO DA MEMORIA DOCOMPUTADOR

        if (LISTA_COMPLETA.size() > 0) {
            txtCodigo.setText("" + LISTA_COMPLETA.get(linha).getCodigo());
            jcSigla.setSelectedItem(LISTA_COMPLETA.get(linha).getSigla());
            txtNomeServidor.setText(LISTA_COMPLETA.get(linha).getNomeServidor());

        }

    }

    private void EXCLUIR() {
        FUNCOES_MODEL model = new FUNCOES_MODEL();
        model.setCodigo(ID);
        FUNCOES_DAO dao = new FUNCOES_DAO();
        dao.EXCLUIR(model);
        Limpar();
        btnSalvar.setEnabled(false);
        btnDeletar.setEnabled(false);
        btnovo.setEnabled(true);

        PREENCHER_TABELA();
    }

}
