/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.medical.screen;

import me.medical.dao.ESPECIALIDADES_MEDICAS_DAO;
import me.medical.model.ESPECIALIDADES_MEDICAS_MODEL;
import me.medical.utils.UpperCaseField;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adriano Zanette
 */
public class TelaCadEspecialidadesMedicas extends javax.swing.JFrame {

    int ID = 0;
    List<ESPECIALIDADES_MEDICAS_MODEL> LISTA_COMPLETA = new ArrayList<>();
    public Connection CONEXAO = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaCadEspecialidadesMedicas
     */
    public TelaCadEspecialidadesMedicas() {
        initComponents();
        setIcon();
        PREENCHER_TABELA();
        letrasemNegrito();
        txtCodigo.setEnabled(false);
        txtEspecialidadesMedicas.setEnabled(false);
        TabelaEspecialidadesMedicas.setEnabled(false);
        txtEspecialidadesMedicas.setDocument(new UpperCaseField(100));
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Receita.png")));
    }
    
    
    
    
    private void Limpar() {

        txtCodigo.setText("");
        txtEspecialidadesMedicas.setText("");
        
    }
    
    // metodo para colocar a letra em negrito
    Font fonte = new Font("Arial", Font.BOLD, 12);

    private void letrasemNegrito() {
        txtEspecialidadesMedicas.setFont(fonte);

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtEspecialidadesMedicas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnovo = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaEspecialidadesMedicas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Especialidades Médicas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro Especialidades Médicas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        jpCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Código :");
        jpCadastro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome da Especialidade Médica");
        jpCadastro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(255, 255, 204));
        txtCodigo.setToolTipText("Código do tipo do produto");
        txtCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jpCadastro.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 30));

        txtEspecialidadesMedicas.setBackground(new java.awt.Color(255, 255, 204));
        txtEspecialidadesMedicas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jpCadastro.add(txtEspecialidadesMedicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 400, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSalvar.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/salvar_1.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/Novo.png"))); // NOI18N
        btnovo.setText("Novo");
        btnovo.setToolTipText("Novo");
        btnovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnovo.setPreferredSize(new java.awt.Dimension(80, 80));
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        btDeletar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/LIMPAR.png"))); // NOI18N
        btDeletar.setText("Deletar");
        btDeletar.setToolTipText("Deletar");
        btDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDeletar.setPreferredSize(new java.awt.Dimension(80, 80));
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        TabelaEspecialidadesMedicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Especialidade Médica"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaEspecialidadesMedicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaEspecialidadesMedicasMouseClicked(evt);
            }
        });
        TabelaEspecialidadesMedicas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaEspecialidadesMedicasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaEspecialidadesMedicas);
        if (TabelaEspecialidadesMedicas.getColumnModel().getColumnCount() > 0) {
            TabelaEspecialidadesMedicas.getColumnModel().getColumn(0).setMinWidth(0);
            TabelaEspecialidadesMedicas.getColumnModel().getColumn(0).setPreferredWidth(0);
            TabelaEspecialidadesMedicas.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 530, 370));

        setSize(new java.awt.Dimension(568, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        GRAVACAO();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        txtEspecialidadesMedicas.setEnabled(true);
        TabelaEspecialidadesMedicas.setEnabled(true);
        Limpar();
        btnovo.setEnabled(false);
        btDeletar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnSalvar.setText("Salvar");
        txtEspecialidadesMedicas.requestFocus();

    }//GEN-LAST:event_btnovoActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed

        int pergunta = JOptionPane.showConfirmDialog(null, "Confirma exclusão?");
        if (pergunta == JOptionPane.YES_OPTION) {
            EXCLUIR();
            Limpar();
        }
        
    }//GEN-LAST:event_btDeletarActionPerformed

    private void TabelaEspecialidadesMedicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaEspecialidadesMedicasMouseClicked
        int linha = TabelaEspecialidadesMedicas.getSelectedRow();
        if (linha >= 0) {
            ID = Integer.parseInt(TabelaEspecialidadesMedicas.getValueAt(linha, 0).toString());
            //PESQUISA_COD_VISUAL();
            PESQUISA_COD_VISUAL_MEMORIA_ESPECIALIDADES_medicas(linha);
            btDeletar.setEnabled(true);
            btnSalvar.setEnabled(true);
            btnSalvar.setText("Alterar");
            btnovo.setEnabled(false);
        }
    }//GEN-LAST:event_TabelaEspecialidadesMedicasMouseClicked

    private void TabelaEspecialidadesMedicasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaEspecialidadesMedicasKeyReleased
        int linha = TabelaEspecialidadesMedicas.getSelectedRow();
        if (linha >= 0) {
            ID = Integer.parseInt(TabelaEspecialidadesMedicas.getValueAt(linha, 0).toString());
            //           PESQUISA_COD_VISUAL();
            PESQUISA_COD_VISUAL_MEMORIA_ESPECIALIDADES_medicas(linha);
            btDeletar.setEnabled(true);
        }
    }//GEN-LAST:event_TabelaEspecialidadesMedicasKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadEspecialidadesMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadEspecialidadesMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadEspecialidadesMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadEspecialidadesMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadEspecialidadesMedicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaEspecialidadesMedicas;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpCadastro;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEspecialidadesMedicas;
    // End of variables declaration//GEN-END:variables

    private void GRAVACAO() {
        
         if (txtEspecialidadesMedicas.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "A especialidade é obrigatório", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }


        ESPECIALIDADES_MEDICAS_MODEL model = new ESPECIALIDADES_MEDICAS_MODEL();
        model.setEspecialidades(txtEspecialidadesMedicas.getText());
        model.setCodigo(ID);
        ESPECIALIDADES_MEDICAS_DAO dao = new ESPECIALIDADES_MEDICAS_DAO();

        if (ID == 0) {
            dao.GRAVAR(model);
            Limpar();
            btnSalvar.setEnabled(false);
            btDeletar.setEnabled(false);
            btnovo.setEnabled(true);
            txtEspecialidadesMedicas.setEnabled(false);
            TabelaEspecialidadesMedicas.setEnabled(false);
        } else {
            dao.ALTERAR(model);
            Limpar();
            btnSalvar.setEnabled(false);
            btDeletar.setEnabled(false);
            btnovo.setEnabled(true);
            txtEspecialidadesMedicas.setEnabled(false);
            TabelaEspecialidadesMedicas.setEnabled(false);
        }
            PREENCHER_TABELA();
        
    }

    
    
        private void PREENCHER_TABELA() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaEspecialidadesMedicas.getModel();
        modelo.setNumRows(0);

        ESPECIALIDADES_MEDICAS_DAO dao = new ESPECIALIDADES_MEDICAS_DAO();
        List<ESPECIALIDADES_MEDICAS_MODEL> lista_dao = dao.LISTA_COMPLETA();
        LISTA_COMPLETA = lista_dao;

        if (lista_dao.size() > 0) {
            for (ESPECIALIDADES_MEDICAS_MODEL leito_model : lista_dao) {
                modelo.addRow(new Object[]{
                    leito_model.getCodigo(),
                    leito_model.getEspecialidades(),});

            }
    
        }
        }
    
         // CLICA NA TABELA E PREENCHE OS CAMPOS
      
        // seta os dados na tabela
    private void PESQUISA_COD_VISUAL_MEMORIA_ESPECIALIDADES_medicas(int linha) {
        // PUXA DIRETO DA MEMORIA DOCOMPUTADOR

        if (LISTA_COMPLETA.size() > 0) {

            txtEspecialidadesMedicas.setText("" + LISTA_COMPLETA.get(linha).getCodigo());
            txtEspecialidadesMedicas.setText(LISTA_COMPLETA.get(linha).getEspecialidades());
            

        }
   
    } 
    
    
    private void EXCLUIR() {
        ESPECIALIDADES_MEDICAS_MODEL model = new ESPECIALIDADES_MEDICAS_MODEL();
        model.setCodigo(ID);
        ESPECIALIDADES_MEDICAS_DAO dao = new ESPECIALIDADES_MEDICAS_DAO();
        dao.EXCLUIR(model);
        Limpar();
        btnSalvar.setEnabled(false);
        btDeletar.setEnabled(false);
        btnovo.setEnabled(true);

       PREENCHER_TABELA();
    }
    
    
    
    
    
}
