/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.medical.screen;

import me.medical.connection.Conectar;
import me.medical.dao.ESPECIALIDADES_DAO;
import me.medical.dao.SERVICOS_DAO;
import me.medical.model.ESPECIALIDADES_MODEL;
import me.medical.model.SERVICOS_MODEL;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adriano Zanette
 */
public class TelaCadAtendimentosDiarios extends javax.swing.JFrame {
  
    
    int ID = 0;
    PreparedStatement ps = null;
    ResultSet rs = null;
    List<ESPECIALIDADES_MODEL> LISTA_COMPLETA = new ArrayList<>();
    List<SERVICOS_MODEL> LISTA_COMPLETAS = new ArrayList<>();
    public Connection CONEXAO = null;
    
  

    /**
     * Creates new form TelaAtendimentosDiarios
     */

    public TelaCadAtendimentosDiarios() {
        initComponents();
        btnSalvar.setEnabled(false);
        btDeletar.setEnabled(false);
        txtCodigo2.setVisible(false);
        jLabelcodigo.setVisible(false);
        setVisible(true);
        setIcon();
        BLOQUEIA_TEXTO();
        populaJComboBoxEspecialidadesMedicas();
        populaJComboBoxSiglaFuncoes();
        populaJComboBoxNomeServidores();
        PREENCHER_TABELA_ESPECIALIDADES();
        PREENCHER_TABELA_SERVICOS();
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Receita.png")));
    }
    

    private void Limpar() {

        txtCodigo.setText("");
        JcEspecialidadesMedicas.setSelectedIndex(0);
        jcTurnoEspecialidades.setSelectedIndex(0);
        jcStatusEspecialidades.setSelectedIndex(0);
        jcTipoServico.setSelectedIndex(0);
        jcTurnoServicos.setSelectedIndex(0);
        jcStatusServicos.setSelectedIndex(0);

    }

    public void BLOQUEIA_TEXTO() {

        txtCodigo.setEnabled(false);
        JcEspecialidadesMedicas.setEnabled(false);
        jcTurnoEspecialidades.setEnabled(false);
        jcStatusEspecialidades.setEnabled(false);
        jcTipoServico.setEnabled(false);
        jcTurnoServicos.setEnabled(false);
        jcStatusServicos.setEnabled(false);
        JcSiglas.setEnabled(false);
        JcNomeAtendente.setEnabled(false);
        TabelaServicos.setEnabled(false);
        TabelaEspecialidades.setEnabled(false);
        
    }

    public void DESBLOQUEIA_TEXTO() {

        txtCodigo.setEnabled(!false);
        JcEspecialidadesMedicas.setEnabled(!false);
        jcTurnoEspecialidades.setEnabled(!false);
        jcStatusEspecialidades.setEnabled(!false);
        jcTipoServico.setEnabled(!false);
        jcTurnoServicos.setEnabled(!false);
        JcSiglas.setEnabled(!false);
        JcNomeAtendente.setEnabled(!false);
        jcStatusServicos.setEnabled(!false);
        TabelaServicos.setEnabled(!false);
        TabelaEspecialidades.setEnabled(!false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        txtCodigo2 = new javax.swing.JTextField();
        jLabelcodigo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcTurnoEspecialidades = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jcStatusEspecialidades = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnovo = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btvoltar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaEspecialidades = new javax.swing.JTable();
        JcEspecialidadesMedicas = new javax.swing.JComboBox<>();
        JcSiglas = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        JcNomeAtendente = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcTurnoServicos = new javax.swing.JComboBox<>();
        jcStatusServicos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcTipoServico = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnovo1 = new javax.swing.JButton();
        btDeletar1 = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        btvoltar2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaServicos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Serviços Disponiveis");
        getContentPane().setLayout(null);

        txtCodigo2.setEditable(false);
        txtCodigo2.setBackground(new java.awt.Color(255, 255, 204));
        txtCodigo2.setToolTipText("Código do tipo do produto");
        txtCodigo2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCodigo2.setEnabled(false);

        jLabelcodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelcodigo.setText("Código :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Especialidade:");

        jcTurnoEspecialidades.setBackground(new java.awt.Color(255, 255, 204));
        jcTurnoEspecialidades.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcTurnoEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Diurno", "Noturno" }));
        jcTurnoEspecialidades.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Turno Especialidade:");

        jcStatusEspecialidades.setBackground(new java.awt.Color(255, 255, 204));
        jcStatusEspecialidades.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcStatusEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Em Atendimento", "Sem Atendimento", " " }));
        jcStatusEspecialidades.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Status Especialidade:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Nome do Médico/Outros");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/Novo.png"))); // NOI18N
        btnovo.setText("Novo");
        btnovo.setToolTipText("Novo");
        btnovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnovo.setPreferredSize(new java.awt.Dimension(80, 80));
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        btDeletar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/LIMPAR.png"))); // NOI18N
        btDeletar.setText("Excluir");
        btDeletar.setToolTipText("Deletar");
        btDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDeletar.setPreferredSize(new java.awt.Dimension(80, 80));
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/salvar_1.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Adcionar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setPreferredSize(new java.awt.Dimension(80, 80));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btvoltar1.setBackground(java.awt.Color.white);
        btvoltar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btvoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btvoltar1.setText("Sair");
        btvoltar1.setToolTipText("Sair");
        btvoltar1.setOpaque(false);
        btvoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvoltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btvoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDeletar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btvoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSalvar, btvoltar1});

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TabelaEspecialidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Especialidades", "Sigla", "Nome do Médico", "Turno Especialidade", "Status Especialidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaEspecialidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaEspecialidadesMouseClicked(evt);
            }
        });
        TabelaEspecialidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaEspecialidadesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaEspecialidades);
        if (TabelaEspecialidades.getColumnModel().getColumnCount() > 0) {
            TabelaEspecialidades.getColumnModel().getColumn(0).setMinWidth(0);
            TabelaEspecialidades.getColumnModel().getColumn(0).setPreferredWidth(0);
            TabelaEspecialidades.getColumnModel().getColumn(0).setMaxWidth(0);
            TabelaEspecialidades.getColumnModel().getColumn(1).setPreferredWidth(100);
            TabelaEspecialidades.getColumnModel().getColumn(2).setPreferredWidth(50);
            TabelaEspecialidades.getColumnModel().getColumn(3).setPreferredWidth(120);
            TabelaEspecialidades.getColumnModel().getColumn(4).setPreferredWidth(50);
            TabelaEspecialidades.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        JcEspecialidadesMedicas.setBackground(new java.awt.Color(255, 255, 204));
        JcEspecialidadesMedicas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JcEspecialidadesMedicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>" }));
        JcEspecialidadesMedicas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        JcSiglas.setBackground(new java.awt.Color(255, 255, 204));
        JcSiglas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JcSiglas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>" }));
        JcSiglas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Sigla:");

        JcNomeAtendente.setBackground(new java.awt.Color(255, 255, 204));
        JcNomeAtendente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JcNomeAtendente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>" }));
        JcNomeAtendente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelcodigo)
                            .addComponent(txtCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcEspecialidadesMedicas, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(JcNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcTurnoEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jcStatusEspecialidades, 0, 188, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11))
                            .addGap(36, 36, 36))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabelcodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JcEspecialidadesMedicas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcTurnoEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JcNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcStatusEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(JcSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("ESPECIALIZAÇÃO", jPanel8);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Código :");

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(255, 255, 204));
        txtCodigo.setToolTipText("Código do tipo do produto");
        txtCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCodigo.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Tipo Serviço:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Turno Serviço:");

        jcTurnoServicos.setBackground(new java.awt.Color(255, 255, 204));
        jcTurnoServicos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcTurnoServicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Diurno", "Noturno" }));
        jcTurnoServicos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jcStatusServicos.setBackground(new java.awt.Color(255, 255, 204));
        jcStatusServicos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcStatusServicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Ativo", "Inativo", "Em manutenção", "Sem Atendimento", "Em Atendimento", " " }));
        jcStatusServicos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Status Servico:");

        jcTipoServico.setBackground(new java.awt.Color(255, 255, 204));
        jcTipoServico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcTipoServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "RAIO X", "ECG", "LABORATÓRIO", "SUTURA" }));
        jcTipoServico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnovo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/Novo.png"))); // NOI18N
        btnovo1.setText("Novo");
        btnovo1.setToolTipText("Novo");
        btnovo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnovo1.setPreferredSize(new java.awt.Dimension(80, 80));
        btnovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovo1ActionPerformed(evt);
            }
        });

        btDeletar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDeletar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/LIMPAR.png"))); // NOI18N
        btDeletar1.setText("Excluir");
        btDeletar1.setToolTipText("Deletar");
        btDeletar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDeletar1.setPreferredSize(new java.awt.Dimension(80, 80));
        btDeletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletar1ActionPerformed(evt);
            }
        });

        btnSalvar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/salvar_1.png"))); // NOI18N
        btnSalvar1.setText("Salvar");
        btnSalvar1.setToolTipText("Adcionar");
        btnSalvar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar1.setPreferredSize(new java.awt.Dimension(80, 80));
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        btvoltar2.setBackground(java.awt.Color.white);
        btvoltar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btvoltar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btvoltar2.setText("Sair");
        btvoltar2.setToolTipText("Sair");
        btvoltar2.setOpaque(false);
        btvoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvoltar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDeletar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btvoltar2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btDeletar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btvoltar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        TabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Tipo Serviço", "Turno Serviço", "Status Serviço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaServicosMouseClicked(evt);
            }
        });
        TabelaServicos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaServicosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(TabelaServicos);
        if (TabelaServicos.getColumnModel().getColumnCount() > 0) {
            TabelaServicos.getColumnModel().getColumn(0).setPreferredWidth(15);
            TabelaServicos.getColumnModel().getColumn(1).setPreferredWidth(150);
            TabelaServicos.getColumnModel().getColumn(2).setPreferredWidth(80);
            TabelaServicos.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jcTipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcTurnoServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jcStatusServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 432, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcTurnoServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcStatusServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(36, 36, 36))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcTipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("SERVIÇOS", jPanel7);

        getContentPane().add(jTabbedPane3);
        jTabbedPane3.setBounds(10, 11, 115, 48);

        setSize(new java.awt.Dimension(1093, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed

        DESBLOQUEIA_TEXTO();
        Limpar();
        btnovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnSalvar.setText("Salvar");
        JcEspecialidadesMedicas.requestFocus();
    }//GEN-LAST:event_btnovoActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed

        int pergunta = JOptionPane.showConfirmDialog(null, "Confirma exclusão?");
        if (pergunta == JOptionPane.YES_OPTION) {
            EXCLUIR_ESPECIALIDADE();
            Limpar();
        }
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        GRAVACAO_ESPECIALIDADES();
        btnovo.setEnabled(true);
        btnSalvar.setEnabled(false);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btvoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvoltar1ActionPerformed
        //Pergunta se o usuário deseja realmente sair do sistema
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja retornar a tela principal ?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btvoltar1ActionPerformed

    private void btnovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovo1ActionPerformed
         DESBLOQUEIA_TEXTO();
        Limpar();
        btnovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnSalvar.setText("Salvar");
        
    }//GEN-LAST:event_btnovo1ActionPerformed

    private void btDeletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletar1ActionPerformed
        int pergunta = JOptionPane.showConfirmDialog(null, "Confirma exclusão?");
        if (pergunta == JOptionPane.YES_OPTION) {
            EXCLUIR_SERVICOS();
            Limpar();
        }
    }//GEN-LAST:event_btDeletar1ActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        GRAVACAO_SERVICOS();
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void btvoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvoltar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btvoltar2ActionPerformed

    private void TabelaEspecialidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaEspecialidadesMouseClicked
        int linha = TabelaEspecialidades.getSelectedRow();
        if (linha >= 0) {
            ID = Integer.parseInt(TabelaEspecialidades.getValueAt(linha, 0).toString());
            //PESQUISA_COD_VISUAL();
            PESQUISA_COD_VISUAL_MEMORIA_ESPECIALIDADES(linha);
            btDeletar.setEnabled(true);
            btnovo.setEnabled(false);
            btnSalvar.setText("Alterar");
        }
    }//GEN-LAST:event_TabelaEspecialidadesMouseClicked

    private void TabelaEspecialidadesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaEspecialidadesKeyReleased
        int linha = TabelaEspecialidades.getSelectedRow();
        if (linha >= 0) {
            ID = Integer.parseInt(TabelaEspecialidades.getValueAt(linha, 0).toString());
            //           PESQUISA_COD_VISUAL();
            PESQUISA_COD_VISUAL_MEMORIA_ESPECIALIDADES(linha);
            btDeletar.setEnabled(true);
        }
    }//GEN-LAST:event_TabelaEspecialidadesKeyReleased

    private void TabelaServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaServicosMouseClicked
        int linha = TabelaServicos.getSelectedRow();
        if (linha >= 0) {
            ID = Integer.parseInt(TabelaServicos.getValueAt(linha, 0).toString());
            //PESQUISA_COD_VISUAL();
            PESQUISA_COD_VISUAL_MEMORIA_SERVICOS(linha);
            btDeletar.setEnabled(true);
            btnSalvar.setEnabled(true);
            btnSalvar1.setText("Alterar");
            btnovo.setEnabled(false);
        }
    }//GEN-LAST:event_TabelaServicosMouseClicked

    private void TabelaServicosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaServicosKeyReleased
        int linha = TabelaServicos.getSelectedRow();
        if (linha >= 0) {
            ID = Integer.parseInt(TabelaServicos.getValueAt(linha, 0).toString());
            //           PESQUISA_COD_VISUAL();
            PESQUISA_COD_VISUAL_MEMORIA_SERVICOS(linha);
            btDeletar.setEnabled(true);
        }
    }//GEN-LAST:event_TabelaServicosKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadAtendimentosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadAtendimentosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadAtendimentosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadAtendimentosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadAtendimentosDiarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcEspecialidadesMedicas;
    private javax.swing.JComboBox<String> JcNomeAtendente;
    private javax.swing.JComboBox<String> JcSiglas;
    private javax.swing.JTable TabelaEspecialidades;
    private javax.swing.JTable TabelaServicos;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btDeletar1;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton btnovo1;
    private javax.swing.JButton btvoltar1;
    private javax.swing.JButton btvoltar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelcodigo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JComboBox<String> jcStatusEspecialidades;
    private javax.swing.JComboBox<String> jcStatusServicos;
    private javax.swing.JComboBox<String> jcTipoServico;
    private javax.swing.JComboBox<String> jcTurnoEspecialidades;
    private javax.swing.JComboBox<String> jcTurnoServicos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo2;
    // End of variables declaration//GEN-END:variables

    
        
     
    
    //------------------------ metodo que popula os comboox do banco----------------   
    public void populaJComboBoxEspecialidadesMedicas() {

        Conectar conec = new Conectar();
        String sql = "Select *from tb_Especialidades_Medicas";
        try {
            ps = conec.CONEXAO.prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                JcEspecialidadesMedicas.addItem(rs.getString("especialidades"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    //------------------------ metodo que popula os comboox do banco----------------   
    public void populaJComboBoxSiglaFuncoes() {

        Conectar conec = new Conectar();
        String sql = "Select *from tb_funcoes";
        try {
            ps = conec.CONEXAO.prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                JcSiglas.addItem(rs.getString("Sigla"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void populaJComboBoxNomeServidores() {

        Conectar conec = new Conectar();
        String sql = "Select *from tb_funcoes";
        try {
            ps = conec.CONEXAO.prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                JcNomeAtendente.addItem(rs.getString("NomeServidor"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    // ESPECIALIDADES 
    private void GRAVACAO_ESPECIALIDADES() {
        
        
        if (JcEspecialidadesMedicas.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "A especialidade é obrigatório", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (JcSiglas.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "A Sigla é obrigatório", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (JcNomeAtendente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "O nome é obrigatório", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
         if (jcTurnoEspecialidades.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "O turno é obrigatório", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         if (jcStatusEspecialidades.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "O status é obrigatório", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        

        ESPECIALIDADES_MODEL model = new ESPECIALIDADES_MODEL();
        model.setEspecialidades(JcEspecialidadesMedicas.getSelectedItem().toString());
        model.setSigla(JcSiglas.getSelectedItem().toString());
        model.setNomeMedico(JcNomeAtendente.getSelectedItem().toString());
        model.setTurnoEspecialidade(jcTurnoEspecialidades.getSelectedItem().toString());
        model.setStatusEspecialidade(jcStatusEspecialidades.getSelectedItem().toString());
        model.setCodigo(ID);

        ESPECIALIDADES_DAO dao = new ESPECIALIDADES_DAO();

        if (ID == 0) {
            dao.GRAVAR(model);
            Limpar();
            btnSalvar.setEnabled(false);
            btDeletar.setEnabled(false);
            btnovo.setEnabled(true);
            BLOQUEIA_TEXTO();
            dispose();
        } else {
            dao.ALTERAR(model);
            Limpar();
            btnSalvar.setEnabled(false);
            btDeletar.setEnabled(false);
            btnovo.setEnabled(true);
            BLOQUEIA_TEXTO();
           
        }

        PREENCHER_TABELA_ESPECIALIDADES();
        
    }

    private void EXCLUIR_ESPECIALIDADE() {
        ESPECIALIDADES_MODEL model = new ESPECIALIDADES_MODEL();
        model.setCodigo(ID);
        ESPECIALIDADES_DAO dao = new ESPECIALIDADES_DAO();
        dao.EXCLUIR(model);
        Limpar();
        btnSalvar.setEnabled(false);
        btDeletar.setEnabled(false);
        btnovo.setEnabled(true);

        PREENCHER_TABELA_ESPECIALIDADES();
    }

    private void PREENCHER_TABELA_ESPECIALIDADES() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaEspecialidades.getModel();
        modelo.setNumRows(0);

        ESPECIALIDADES_DAO dao = new ESPECIALIDADES_DAO();
        List<ESPECIALIDADES_MODEL> lista_dao = dao.LISTA_COMPLETA();
        LISTA_COMPLETA = lista_dao;

        if (lista_dao.size() > 0) {
            for (ESPECIALIDADES_MODEL especialidades_model : lista_dao) {
                modelo.addRow(new Object[]{
                    especialidades_model.getCodigo(),
                    especialidades_model.getEspecialidades(),
                    especialidades_model.getSigla(),
                    especialidades_model.getNomeMedico(),
                    especialidades_model.getTurnoEspecialidade(),
                    especialidades_model.getStatusEspecialidade(),});

            }

        }
    }

    // SERVICOS 
    private void GRAVACAO_SERVICOS() {

        
        if (jcTipoServico.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "O tipo de serviço é obrigatório", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (jcTurnoServicos.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "O turno do serviço é obrigatório", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (jcStatusServicos.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "O status do serviço é obrigatório", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        SERVICOS_MODEL model = new SERVICOS_MODEL();
        model.setTipoServico(jcTipoServico.getSelectedItem().toString());
        model.setTurnoServico(jcTurnoServicos.getSelectedItem().toString());
        model.setStatusServico(jcStatusServicos.getSelectedItem().toString());
        model.setCodigo(ID);

        SERVICOS_DAO dao = new SERVICOS_DAO();

        if (ID == 0) {
            dao.GRAVAR(model);
            Limpar();
            btnSalvar.setEnabled(false);
            btDeletar.setEnabled(false);
            btnovo.setEnabled(true);
            BLOQUEIA_TEXTO();
        } else {
            dao.ALTERAR(model);
            Limpar();
            btnSalvar.setEnabled(false);
            btDeletar.setEnabled(false);
            btnovo.setEnabled(true);
            BLOQUEIA_TEXTO();
        }

        PREENCHER_TABELA_SERVICOS();
        
    }

    private void EXCLUIR_SERVICOS() {
        SERVICOS_MODEL model = new SERVICOS_MODEL();
        model.setCodigo(ID);
        SERVICOS_DAO dao = new SERVICOS_DAO();
        dao.EXCLUIR(model);
        Limpar();
        btnSalvar.setEnabled(false);
        btDeletar.setEnabled(false);
        btnovo.setEnabled(true);

        PREENCHER_TABELA_SERVICOS();
    }

    private void PREENCHER_TABELA_SERVICOS() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaServicos.getModel();
        modelo.setNumRows(0);

        SERVICOS_DAO dao = new SERVICOS_DAO();
        List<SERVICOS_MODEL> lista_dao = dao.LISTA_COMPLETA();
        LISTA_COMPLETAS = lista_dao;

        if (lista_dao.size() > 0) {
            for (SERVICOS_MODEL servicos_model : lista_dao) {
                modelo.addRow(new Object[]{
                    servicos_model.getCodigo(),
                    servicos_model.getTipoServico(),
                    servicos_model.getTurnoServico(),
                    servicos_model.getStatusServico(),});

            }

        }
    }

    // CLICA NA TABELA E PREENCHE OS CAMPOS
    // seta os dados na tabela
    private void PESQUISA_COD_VISUAL_MEMORIA_ESPECIALIDADES(int linha) {
        // PUXA DIRETO DA MEMORIA DOCOMPUTADOR

        if (LISTA_COMPLETA.size() > 0) {

            txtCodigo2.setText("" + LISTA_COMPLETA.get(linha).getCodigo());
            JcEspecialidadesMedicas.setSelectedItem(LISTA_COMPLETA.get(linha).getEspecialidades());
            JcSiglas.setSelectedItem(LISTA_COMPLETA.get(linha).getSigla());
            JcNomeAtendente.setSelectedItem(LISTA_COMPLETA.get(linha).getNomeMedico());
            jcTurnoEspecialidades.setSelectedItem(LISTA_COMPLETA.get(linha).getTurnoEspecialidade());
            jcStatusEspecialidades.setSelectedItem(LISTA_COMPLETA.get(linha).getStatusEspecialidade());

        }

    }

    // seta os dados na tabela
    private void PESQUISA_COD_VISUAL_MEMORIA_SERVICOS(int linha) {
        // PUXA DIRETO DA MEMORIA DOCOMPUTADOR

        if (LISTA_COMPLETAS.size() > 0) {

            txtCodigo.setText("" + LISTA_COMPLETAS.get(linha).getCodigo());
            jcTipoServico.setSelectedItem(LISTA_COMPLETAS.get(linha).getTipoServico());
            jcTurnoServicos.setSelectedItem(LISTA_COMPLETAS.get(linha).getTurnoServico());
            jcStatusServicos.setSelectedItem(LISTA_COMPLETAS.get(linha).getStatusServico());
        }

    }

}
