/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.medical.screen;

import java.awt.Toolkit;

/**
 *
 * @author Adriano Zanette
 */
public class TelaPainelAcesoRapidoPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TelaPainelAcesoRapido
     */
    public TelaPainelAcesoRapidoPaciente() {
        initComponents();
        setIcon();
    }
    
     private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Receita.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenucadastros2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenucadastros3 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenucadastros2.setBackground(new java.awt.Color(255, 255, 255));
        jMenucadastros2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenucadastros2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Evolucao.png"))); // NOI18N
        jMenucadastros2.setText("Evolução Paciente");
        jMenucadastros2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenucadastros2.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jMenucadastros2.setMaximumSize(new java.awt.Dimension(210, 32767));
        jMenucadastros2.setName(""); // NOI18N
        jMenucadastros2.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenucadastros2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenucadastros2MouseClicked(evt);
            }
        });
        jMenucadastros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenucadastros2ActionPerformed(evt);
            }
        });

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem8.setText("Cadastrar Evolução");
        jMenuItem8.setPreferredSize(new java.awt.Dimension(200, 27));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenucadastros2.add(jMenuItem8);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem13.setText("Visualizar Evolução dos Pacientes");
        jMenuItem13.setPreferredSize(new java.awt.Dimension(230, 27));
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenucadastros2.add(jMenuItem13);

        jMenuBar1.add(jMenucadastros2);

        jMenucadastros3.setBackground(new java.awt.Color(255, 255, 255));
        jMenucadastros3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenucadastros3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensTelas/camaHospital.png"))); // NOI18N
        jMenucadastros3.setText("Liberação do Paciente");
        jMenucadastros3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenucadastros3.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jMenucadastros3.setMaximumSize(new java.awt.Dimension(230, 32767));
        jMenucadastros3.setName(""); // NOI18N
        jMenucadastros3.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenucadastros3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenucadastros3MouseClicked(evt);
            }
        });
        jMenucadastros3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenucadastros3ActionPerformed(evt);
            }
        });

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem19.setText("Alta Hospitalar");
        jMenuItem19.setPreferredSize(new java.awt.Dimension(200, 27));
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenucadastros3.add(jMenuItem19);

        jMenuBar1.add(jMenucadastros3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salir.png"))); // NOI18N
        jMenu2.setText("Sair");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(524, 83));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        TelaGeralPacientesEvolucao tela = new TelaGeralPacientesEvolucao();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        TelaVisualizarEvolucao tela = new TelaVisualizarEvolucao();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenucadastros2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenucadastros2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenucadastros2MouseClicked

    private void jMenucadastros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenucadastros2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenucadastros2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        TelaGeralPacientesIternadosEnfermagem tela = new TelaGeralPacientesIternadosEnfermagem();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenucadastros3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenucadastros3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenucadastros3MouseClicked

    private void jMenucadastros3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenucadastros3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenucadastros3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPainelAcesoRapidoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPainelAcesoRapidoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPainelAcesoRapidoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPainelAcesoRapidoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPainelAcesoRapidoPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu jMenucadastros2;
    private javax.swing.JMenu jMenucadastros3;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    // End of variables declaration//GEN-END:variables
}
